### ISSUE TITLE
Google dropping support for Documents List API on April 20th 2015

### ISSUE THREAD

**Issue by fabiant7t** [mbrenig/SheetSync#7]
Hi Mark,

Google will drop support for the Documents List API in a week from now. I guess SheetSync will stop working then and wonder if there is a migration plan to the Drive API? 

Best,
Fabian

**Comment by fabiant7t** [comment]
Hi Mark, since it continues to work, I assume it's not using it.

Best,
Fabian

**Comment by mbrenig** [comment]
FYI this is now fixed in the master branch and documented here: http://sheetsync.readthedocs.org/en/latest/getting_started.html#setting-up-oauth-2-0-access

**Comment by fabiant7t** [comment]
Thanks a lot, @mbrenig
